Repository wecode-bootcamp-korea/13-coderoasters-backend, pull requests merged in 2020-11, with the labels that each got.

#1 Add : User Sign Up, Log In API
  controllers/UserController.js
  controllers/index.js
  middleware/index.js
  middleware/validateToken.js
  prisma/schema.prisma
  routes/UserRouter.js
  routes/index.js
  server.js
  services/UserService.js
  services/index.js
  utils/makeDataForCreate.js
Labels: Status: Accepted

#2 Add : 상품 정보 조회 API 작성
  app.js
  controllers/ProductController.js
  controllers/index.js
  routes/ProductRouter.js
  routes/index.js
  server.js
  services/ProductService.js
  services/index.js
  utils/errorGenerator.js
  utils/makeDataForFilter.js
  utils/makeDataForSort.js
  utils/typeCaster.js
Labels: Status: 리뷰 요청

#3 Edit : 테이블 컬럼명 수정 & typo 수정
  code_roasters.sql
  prisma/schema.prisma
  services/ProductService.js
Labels: Status: Accepted

#4 Add : Cart API
  app.js
  code_roasters.sql
  controllers/CartController.js
  controllers/index.js
  package-lock.json
  package.json
  prisma/schema.prisma
  routes/CartRouter.js
  routes/index.js
  services/CartService.js
  services/index.js
  utils/index.js
  utils/validateFields.js
Labels: Status: Rebase 요청

#6 Add : 구글 로그인 추가
  code_roasters.sql
  controllers/UserController.js
  middleware/index.js
  middleware/validateGoogleToken.js
  middleware/validateToken.js
  package-lock.json
  package.json
  prisma/schema.prisma
  routes/UserRouter.js
Labels: Status: Accepted

#5 Add : coffees 테이블에 cluster_id 필드 추가, cluster_id 업데이트 자동화
  code_roasters.sql
  controllers/ProductController.js
  prisma/schema.prisma
  routes/ProductRouter.js
  services/ProductService.js
  utils/assignCluster.js
Labels: Status: 리뷰 요청

#7 Add : 커피 추천 API 작성
  controllers/ProductController.js
  routes/ProductRouter.js
  services/ProductService.js
  utils/makeDataForRecommend.js
Labels: Status: Accepted

#9 Edit : 프론트 요청으로 ProductController & ProductService 수정
  controllers/ProductController.js
  services/ProductService.js
Labels: Status: 리뷰 요청

#14 Add : User API UNIT TEST 추가
  code_roasters.sql
  controllers/CartController.js
  controllers/UserController.js
  controllers/UserController.test.js
  package-lock.json
  package.json
  routes/CartRouter.js
Labels: Status: 리뷰 요청

#11 Edit : hotfixes
  .dockerignore
  Dockerfile
  controllers/CartController.js
  controllers/ProductController.js
  controllers/UserController.js
  routes/ProductRouter.js
  routes/UserRouter.js
  services/ProductService.js
  utils/makeDataForRecommend.js
  utils/makeDataForSort.js
Labels: Status: 리뷰 요청
